// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//Firebase options is for the target platforms
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrdDGLOOsjDXWP14-1pL6-ewqWqlm94Cw',
    appId: '1:18392050171:web:fd0da64392111458c5435e',
    messagingSenderId: '18392050171',
    projectId: 'the-coterie-17b54',
    authDomain: 'the-coterie-17b54.firebaseapp.com',
    storageBucket: 'the-coterie-17b54.firebasestorage.app',
    measurementId: 'G-WL1LD1D2DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiRfeR9I2f3Svz5hS0Z9A8PhKDG2tGUCY',
    appId: '1:18392050171:android:af612ba7da41609ec5435e',
    messagingSenderId: '18392050171',
    projectId: 'the-coterie-17b54',
    storageBucket: 'the-coterie-17b54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpkSPfDk3U9x8VcdpbS7ZHnV_7vMW1nTQ',
    appId: '1:18392050171:ios:6dc7ad5ba8adc564c5435e',
    messagingSenderId: '18392050171',
    projectId: 'the-coterie-17b54',
    storageBucket: 'the-coterie-17b54.firebasestorage.app',
    iosBundleId: 'com.thecoterie.theCoterieTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpkSPfDk3U9x8VcdpbS7ZHnV_7vMW1nTQ',
    appId: '1:18392050171:ios:6dc7ad5ba8adc564c5435e',
    messagingSenderId: '18392050171',
    projectId: 'the-coterie-17b54',
    storageBucket: 'the-coterie-17b54.firebasestorage.app',
    iosBundleId: 'com.thecoterie.theCoterieTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrdDGLOOsjDXWP14-1pL6-ewqWqlm94Cw',
    appId: '1:18392050171:web:6140591b174e6d1dc5435e',
    messagingSenderId: '18392050171',
    projectId: 'the-coterie-17b54',
    authDomain: 'the-coterie-17b54.firebaseapp.com',
    storageBucket: 'the-coterie-17b54.firebasestorage.app',
    measurementId: 'G-11Q9HRK6NF',
  );
}
